"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { workspaceClient, getFriends } from "@/lib/demo-data";

const friendSchema = z.object({ preferredName: z.string().trim().min(1).max(60), nickname: z.string().trim().max(60).optional(), pronouns: z.string().trim().max(60).optional(), university: z.string().trim().min(1).max(100), campus: z.string().trim().max(100).optional(), degreeProgram: z.string().trim().max(100).optional(), yearOfStudy: z.string().trim().max(30).optional(), closeness: z.coerce.number().int().min(1).max(5), crush: z.enum(["none", "friends", "crush", "dating", "past"]), howWeMet: z.string().trim().min(1), privateNote: z.string().trim().max(2000).optional(), instagram: z.string().regex(/^[a-zA-Z0-9._]{1,30}$/).optional(), snapchat: z.string().regex(/^[a-zA-Z0-9._-]{1,50}$/).optional() });
const eventSchema = z.object({ title: z.string().trim().min(1).max(120), happenedAt: z.coerce.date(), channel: z.enum(["in_person", "call", "text", "social", "class", "other"]), hangoutType: z.string().trim().max(40).optional(), location: z.string().trim().max(120).optional(), notes: z.string().trim().max(2000).optional(), vibe: z.coerce.number().int().min(1).max(5).optional(), attendeeIds: z.array(z.string().uuid()).min(1) });
const blank = (value: FormDataEntryValue | null) => typeof value === "string" && value.trim() ? value.trim() : undefined;
async function context() { const result = await workspaceClient(); if (!result.workspaceId) throw new Error("Your demo workspace is still being created. Please try again."); return result; }
const refresh = (...paths: string[]) => paths.forEach((path) => revalidatePath(path));

export async function createFriend(formData: FormData) {
  const parsed = friendSchema.parse({ preferredName: formData.get("preferredName"), nickname: blank(formData.get("nickname")), pronouns: blank(formData.get("pronouns")), university: formData.get("university") || "UNSW", campus: blank(formData.get("campus")), degreeProgram: blank(formData.get("degreeProgram")), yearOfStudy: blank(formData.get("yearOfStudy")), closeness: formData.get("closeness"), crush: formData.get("crush") || "none", howWeMet: formData.get("howWeMet") || "other", privateNote: blank(formData.get("privateNote")), instagram: blank(formData.get("instagram"))?.replace(/^@/, ""), snapchat: blank(formData.get("snapchat"))?.replace(/^@/, "") });
  const { supabase, workspaceId } = await context(); const points = [parsed.instagram && { kind: "instagram", value: parsed.instagram, label: `@${parsed.instagram}` }, parsed.snapchat && { kind: "snapchat", value: parsed.snapchat, label: `@${parsed.snapchat}` }].filter(Boolean);
  const { data, error } = await supabase.from("friends").insert({ workspace_id: workspaceId, preferred_name: parsed.preferredName, nickname: parsed.nickname, pronouns: parsed.pronouns, university: parsed.university, campus: parsed.campus, degree_program: parsed.degreeProgram, year_of_study: parsed.yearOfStudy, closeness: parsed.closeness, crush: parsed.crush, my_intent: ["crush", "dating"].includes(parsed.crush) ? "date" : "friend", how_we_met: parsed.howWeMet, private_note: parsed.privateNote, contact_points: points }).select("id").single();
  if (error) throw error; refresh("/", "/friends", "/catchup"); redirect(`/friends/${data.id}`);
}
export async function createEvent(formData: FormData) {
  const parsed = eventSchema.parse({ title: formData.get("title"), happenedAt: formData.get("happenedAt"), channel: formData.get("channel"), hangoutType: blank(formData.get("hangoutType")), location: blank(formData.get("location")), notes: blank(formData.get("notes")), vibe: blank(formData.get("vibe")), attendeeIds: formData.getAll("attendeeIds").map(String) }); const { supabase, workspaceId } = await context();
  const { data: event, error } = await supabase.from("events").insert({ workspace_id: workspaceId, title: parsed.title, happened_at: parsed.happenedAt.toISOString(), channel: parsed.channel, hangout_type: parsed.hangoutType, location: parsed.location, notes: parsed.notes, vibe: parsed.vibe }).select("id").single(); if (error) throw error;
  const { error: attendeeError } = await supabase.from("event_attendees").insert(parsed.attendeeIds.map((friend_id) => ({ workspace_id: workspaceId, event_id: event.id, friend_id }))); if (attendeeError) throw attendeeError;
  const inPerson = parsed.channel === "in_person" || parsed.channel === "class"; for (const id of parsed.attendeeIds) await supabase.from("friends").update({ last_contacted_at: parsed.happenedAt.toISOString(), ...(inPerson ? { last_seen_in_person_at: parsed.happenedAt.toISOString() } : {}) }).eq("id", id).eq("workspace_id", workspaceId);
  refresh("/", "/friends", "/events", "/catchup"); redirect("/events");
}
export async function generateSuggestions() { const friends = await getFriends(); const { supabase, workspaceId } = await context(); await supabase.from("suggestions").delete().eq("workspace_id", workspaceId).eq("status", "pending"); const ideas = friends.slice(0, 6).map((friend, index) => ({ workspace_id: workspaceId, friend_id: friend.id, title: `${friend.preferred_name} + ${["mid-sem drinks", "society BBQ", "Newtown gig", "beach day"][index % 4]} 🍻`, detail: `Make a low-stakes plan around ${friend.interests[0] || friend.societies[0] || "campus life"}.`, template: "demo" })); if (ideas.length) { const { error } = await supabase.from("suggestions").insert(ideas); if (error) throw error; } revalidatePath("/suggestions"); }
export async function updateSuggestionStatus(formData: FormData) { const id = z.string().uuid().parse(formData.get("id")); const status = z.enum(["saved", "dismissed", "went"]).parse(formData.get("status")); const { supabase, workspaceId } = await context(); const { data, error } = await supabase.from("suggestions").update({ status }).eq("id", id).eq("workspace_id", workspaceId).select("friend_id,title,detail").single(); if (error) throw error; if (status === "went") { const at = new Date().toISOString(); const { data: event, error: eventError } = await supabase.from("events").insert({ workspace_id: workspaceId, title: data.title, notes: data.detail, happened_at: at, channel: "in_person", hangout_type: "other" }).select("id").single(); if (eventError) throw eventError; await supabase.from("event_attendees").insert({ workspace_id: workspaceId, event_id: event.id, friend_id: data.friend_id }); await supabase.from("friends").update({ last_contacted_at: at, last_seen_in_person_at: at }).eq("id", data.friend_id).eq("workspace_id", workspaceId); refresh("/", "/events", "/friends"); } revalidatePath("/suggestions"); }
