"use client";

import { useState } from "react";
import type { Activity, WorkspaceState } from "@/lib/workspace";

const days = ["Mon 16", "Tue 17", "Wed 18", "Thu 19", "Fri 20", "Sat 21", "Sun 22"];
const hours = ["9 AM", "10 AM", "11 AM", "12 PM", "1 PM", "2 PM", "3 PM", "4 PM", "5 PM", "6 PM", "7 PM", "8 PM"];
const calendarEvents = [
  { title: "Studio stand-up", day: 0, start: 1, duration: 1, tone: "blue", details: "A focused work block. No action needed." }, { title: "Lunch with Priya", day: 1, start: 3, duration: 1, tone: "rose", details: "Keep the café booking, then take a short walk together." }, { title: "Run club", day: 2, start: 8, duration: 2, tone: "violet", suggested: true, details: "Invite Isla for the 5:30pm beginner loop, then stay for the post-run drink." }, { title: "Dinner at 6", day: 3, start: 9, duration: 2, tone: "orange", details: "A low-key dinner reservation." }, { title: "Design review", day: 4, start: 2, duration: 2, tone: "green", details: "Bring the new flow and leave time for decisions." }, { title: "Open studio", day: 5, start: 5, duration: 2, tone: "blue", details: "Drop in before the clay social begins." }, { title: "Beach walk", day: 6, start: 3, duration: 2, tone: "rose", details: "Meet at the kiosk, then walk north along the water." },
];
type Detail = { title: string; location: string; time: string; detail: string; kind: "suggestion" | "event" };

export function EventFeed({ state, onPlan }: { state: WorkspaceState; onPlan: () => void }) {
  const [selected, setSelected] = useState<Detail | null>(null);
  return <section className="calendar-workspace" aria-label="Plan">
    <header className="calendar-header"><div><p className="calendar-kicker">Your week</p><h1>Make room for people.</h1></div><button className="google-calendar-status" type="button" aria-label="Google Calendar sample view"><span aria-hidden="true" />Google Calendar <b>Sample</b></button></header>
    <section className="weekly-calendar" aria-label="Google Calendar weekly view"><div className="calendar-corner"><button type="button" aria-label="Previous week">‹</button><strong>Sep 16–22</strong><button type="button" aria-label="Next week">›</button></div><div className="calendar-days">{days.map((day, index) => <div className={index === 2 ? "calendar-day-label today" : "calendar-day-label"} key={day}><small>{day.split(" ")[0]}</small><strong>{day.split(" ")[1]}</strong></div>)}</div><div className="calendar-times">{hours.map((hour) => <span key={hour}>{hour}</span>)}</div><div className="calendar-grid" role="grid" aria-label="Week of September 16"><div className="now-line" aria-hidden="true" />{calendarEvents.map((event) => <button key={event.title} className={`calendar-event ${event.tone}${event.suggested ? " ai-suggested" : ""}`} style={{ "--calendar-day": event.day, "--calendar-start": event.start, "--calendar-duration": event.duration } as React.CSSProperties} onClick={() => setSelected({ title: event.suggested ? "AI suggestion: Run club with Isla" : event.title, location: event.suggested ? "Darling Harbour" : "Your calendar", time: `${days[event.day]} · ${hours[event.start]}`, detail: event.details, kind: event.suggested ? "suggestion" : "event" })}>{event.suggested && <i>AI pick</i>}{event.title}</button>)}</div></section>
    <section className="recommended-events" aria-labelledby="recommended-heading"><div className="recommendations-heading"><div><p className="calendar-kicker">For your circle</p><h2 id="recommended-heading">Events worth doing together</h2></div></div><div className="event-grid">{state.activities.map((event, index) => { const details = event.details ?? "This week"; const people = suggestedPeople(event, state); const names = people.map((friend) => friend.displayName.split(" ")[0]).join(", "); return <button className="event-card" key={event.id} onClick={() => setSelected({ title: event.title, location: event.location ?? "Location to confirm", time: details, detail: `This matches ${names} based on the interests you saved. Pick a time, then make an editable plan draft.`, kind: "event" })}><span className={`event-art theme-${index % 8}`}><span>{event.tags[0] ?? "Plan"}</span></span><strong>{event.title}</strong><small>{event.location ?? "Location to confirm"} · {details}</small><small className="event-fits">Fits {names}</small></button>; })}</div></section>
    {selected && <aside className="event-detail-sheet" aria-live="polite"><button className="invite-close" onClick={() => setSelected(null)} aria-label="Close event details">×</button>{selected.kind === "suggestion" && <p className="detail-label">AI suggestion</p>}<h2>{selected.title}</h2><p className="detail-meta">{selected.time} · {selected.location}</p><p>{selected.detail}</p><button className="invite-button" onClick={onPlan}>Make a draft</button></aside>}
  </section>;
}

function suggestedPeople(event: Activity, state: WorkspaceState) { const matches = state.friends.filter((friend) => state.memoryFacts.some((fact) => fact.friendId === friend.id && event.tags.some((tag) => fact.value.toLowerCase().includes(tag)))); return (matches.length ? matches : state.friends).slice(0, 3); }
