"use client";

import { useState } from "react";
import { resolveFriendReference } from "@/lib/extraction";
import type { WorkspaceState } from "@/lib/workspace";

export function ExtractionReview({ state, onExtract, onApprove, onReject, onDeleteProposal, onEditMemory, onForgetMemory, onMergeMemories }: { state: WorkspaceState; onExtract: (noteId: string) => void; onApprove: (id: string) => void; onReject: (id: string) => void; onDeleteProposal: (id: string) => void; onEditMemory: (id: string, value: string) => void; onForgetMemory: (id: string) => void; onMergeMemories: (primaryId: string, duplicateId: string) => void }) {
  const [edits, setEdits] = useState<Record<string, string>>({});
  const friendName = (id: string) => state.friends.find((friend) => friend.id === id)?.displayName ?? "Deleted friend";
  const pending = state.factProposals.filter((item) => item.status === "pending");
  return <><section className="page-heading"><p className="eyebrow">Grounded extraction</p><h1>Review what a local adapter found.</h1><p>The adapter proposes only source-linked facts. It cannot save a memory or trigger a reminder.</p></section><section className="records-section"><h2>Local extraction</h2>{state.notes.map((note) => { const resolution = resolveFriendReference(note.text, state.friends); return <article className="proposal" key={note.id}><p>{note.text}</p>{resolution.kind === "ambiguous" ? <p className="empty">Clarification needed: this note could refer to {resolution.friendIds.map(friendName).join(" or ")}. No proposal was created.</p> : <button className="secondary" onClick={() => onExtract(note.id)}>Run offline fixture extractor</button>}</article>; })}</section><section className="records-section"><h2>Pending proposals</h2>{pending.length ? pending.map((proposal) => <article className="proposal" key={proposal.id}><p className="eyebrow">{friendName(proposal.friendId)} · {proposal.adapter} · {Math.round(proposal.confidence * 100)}% confidence</p><strong>{proposal.type}: {proposal.value}</strong><p>Source: “{proposal.sourceSpan.text}” in the linked note. Suggested intent: {proposal.suggestedIntent}.</p><div className="button-row"><button className="primary" onClick={() => onApprove(proposal.id)}>Approve as memory</button><button className="secondary" onClick={() => onReject(proposal.id)}>Reject</button><button className="danger-link" onClick={() => onDeleteProposal(proposal.id)}>Delete proposal</button></div></article>) : <p className="empty">Nothing is waiting for review.</p>}</section><section className="records-section"><h2>Confirmed memories</h2>{state.memoryFacts.length ? state.memoryFacts.map((memory) => <article className="proposal" key={memory.id}><p className="eyebrow">{friendName(memory.friendId)} · source note · {memory.adapter}</p><label>Edit memory<input value={edits[memory.id] ?? memory.value} onChange={(event) => setEdits({ ...edits, [memory.id]: event.target.value })}/></label><p className="quiet">Original confidence: {Math.round(memory.confidence * 100)}%. Previous wording: {memory.editHistory.length || "none"}.</p><div className="button-row"><button className="secondary" onClick={() => onEditMemory(memory.id, edits[memory.id] ?? memory.value)}>Save edit</button>{state.memoryFacts.filter((other) => other.friendId === memory.friendId && other.id !== memory.id).map((other) => <button className="secondary" key={other.id} onClick={() => onMergeMemories(memory.id, other.id)}>Merge {other.value}</button>)}<button className="danger-link" onClick={() => onForgetMemory(memory.id)}>Forget memory</button></div></article>) : <p className="empty">No memories have been confirmed yet.</p>}</section></>;
}
