"use client";

import { useState } from "react";
import { getActivityMatches, getPromptEligibility, isFresh, JsonFeedPublicEventsAdapter, type PublicEvent } from "@/lib/planning";
import type { Activity, WorkspaceState } from "@/lib/workspace";

const dateTime = (value?: string) => value ? new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "Time not supplied";

export function Planning({ state, onPrompt, onPromptEnabled, onAddActivity, onCreatePlan, onPlanOutcome }: { state: WorkspaceState; onPrompt: (friendId: string, input: { state: "snoozed" | "dismissed"; reason: string; snoozedUntil?: string }) => void; onPromptEnabled: (friendId: string, enabled: boolean) => void; onAddActivity: (input: Omit<Activity, "id" | "retrievedAt">) => void; onCreatePlan: (input: { friendId: string; activityId?: string; message: string }) => void; onPlanOutcome: (planId: string, status: "planned" | "met" | "not-now") => void }) {
  const [friendId, setFriendId] = useState(state.friends.find((friend) => !friend.archived)?.id ?? "");
  const [idea, setIdea] = useState(""); const [details, setDetails] = useState(""); const [location, setLocation] = useState(""); const [startsAt, setStartsAt] = useState("");
  const [activityId, setActivityId] = useState(""); const [message, setMessage] = useState(""); const [searchStatus, setSearchStatus] = useState<string | null>(null); const [copyStatus, setCopyStatus] = useState<string | null>(null);
  const activeFriends = state.friends.filter((friend) => !friend.archived);
  const friend = activeFriends.find((item) => item.id === friendId) ?? activeFriends[0];
  const eligibility = friend ? getPromptEligibility(state, friend) : null;
  const matches = friend ? getActivityMatches(state, friend.id) : [];
  const activities = matches.map((match) => match.activity);
  const addIdea = (event: React.FormEvent) => { event.preventDefault(); onAddActivity({ title: idea, details, location, startsAt: startsAt || undefined, tags: [], source: "manual" }); setIdea(""); setDetails(""); setLocation(""); setStartsAt(""); };
  const search = async () => { if (!friend) return; setSearchStatus("Looking for public events. Nothing is sent until you choose this search."); try { const range = eventSearchRange(); const results = await new JsonFeedPublicEventsAdapter().findActivities({ city: state.city, query: eligibility?.relevantContext.join(" ") || friend.displayName, ...range }); results.forEach((event) => onAddActivity(toActivity(event))); setSearchStatus(results.length ? `${results.length} public event${results.length === 1 ? "" : "s"} added for your review.` : "No public events matched. Add a manual idea instead."); } catch (error) { setSearchStatus(error instanceof Error ? error.message : "Public events could not be loaded. Add a manual idea instead."); } };
  const copyDraft = async (draft: string) => { try { await navigator.clipboard.writeText(draft); setCopyStatus("Draft copied. Choose your own channel when you are ready."); } catch { setCopyStatus("Copy is unavailable in this browser. Select the draft and use your device’s copy command."); } };
  return <><section className="page-heading"><p className="eyebrow">In-person planning</p><h1>A reason, never a grade.</h1><p>Only your cadence, explicit meetups, confirmed context, and plan outcomes shape this local suggestion.</p></section>
    {!friend ? <p className="empty">Add someone to your circle before making a plan.</p> : <><section className="planning-picker"><label>Plan with<select value={friend.id} onChange={(event) => setFriendId(event.target.value)}>{activeFriends.map((item) => <option key={item.id} value={item.id}>{item.displayName}</option>)}</select></label></section>
      <section className="reason-card" aria-live="polite"><p className="eyebrow">Why this appeared</p><h2>{eligibility?.eligible ? `A gentle nudge for ${friend.displayName}` : `No nudge for ${friend.displayName}`}</h2><p>{eligibility?.reason}</p>{eligibility?.eligible && <div className="button-row"><button className="secondary" onClick={() => onPrompt(friend.id, { state: "snoozed", reason: eligibility.reason, snoozedUntil: dateAfterDays(7) })}>Snooze for 7 days</button><button className="secondary" onClick={() => onPrompt(friend.id, { state: "dismissed", reason: eligibility.reason })}>Dismiss</button><button className="danger-link" onClick={() => onPromptEnabled(friend.id, false)}>Turn reminders off</button></div>}{!friend.promptEnabled && <button className="secondary" onClick={() => onPromptEnabled(friend.id, true)}>Turn reminders back on</button>}</section>
      <section className="two-column"><form className="form-stack panel" onSubmit={addIdea}><h2>Manual activity idea</h2><p>A complete offline path. It does not need an event provider.</p><label>Idea<input required value={idea} onChange={(event) => setIdea(event.target.value)} placeholder="Pottery night"/></label><label>Why it fits, optional<input value={details} onChange={(event) => setDetails(event.target.value)} placeholder="A shared intention to make things"/></label><label>Location, optional<input value={location} onChange={(event) => setLocation(event.target.value)} placeholder="Inner West studio"/></label><label>Time, optional<input type="datetime-local" value={startsAt} onChange={(event) => setStartsAt(event.target.value)}/></label><button className="secondary" type="submit">Save local idea</button></form>
        <section className="panel"><h2>Optional public events</h2><p>Search is user-initiated. If the configured public feed is unavailable or empty, no data is required for planning.</p><button className="secondary" onClick={search}>Search public events</button>{searchStatus && <p className="quiet" role="status">{searchStatus}</p>}</section></section>
      <section className="records-section"><h2>Ideas grounded in confirmed context</h2>{matches.length ? matches.map(({ activity, matchedContext }) => <article className="proposal activity-row" key={activity.id}><div><strong>{activity.title}</strong><p>{activity.details || "No further details."}</p><p className="quiet">Matches: {matchedContext.join(", ")} · {activity.location || "Location not supplied"} · {dateTime(activity.startsAt)} · {activity.source === "public-events" ? (isFresh(activity) ? "Fresh public result" : "Public result may be out of date") : "Local idea"}</p>{activity.sourceUrl && <a href={activity.sourceUrl} target="_blank" rel="noreferrer">View source</a>}</div><button className="secondary" onClick={() => setActivityId(activity.id)}>Use in draft</button></article>) : <p className="empty">No activity matches confirmed shared interests or intentions yet. Add a local idea, or confirm context in Review.</p>}</section>
      <form className="form-stack panel plan-form" onSubmit={(event) => { event.preventDefault(); onCreatePlan({ friendId: friend.id, activityId: activityId || undefined, message }); setMessage(""); }}><h2>Editable plan draft</h2><p>Saving a draft does not send a message, create a calendar event, or mean the other person has agreed.</p><label>Activity, optional<select value={activityId} onChange={(event) => setActivityId(event.target.value)}><option value="">No activity selected</option>{activities.map((activity) => <option key={activity.id} value={activity.id}>{activity.title}</option>)}</select></label><label>Draft message<textarea required rows={3} value={message} onChange={(event) => setMessage(event.target.value)} placeholder={`Want to try that idea together next week, ${friend.displayName}?`}/></label><button className="primary" type="submit">Save draft, do not send</button></form>
      <section className="records-section"><h2>Explicit plan outcomes</h2>{state.planDrafts.filter((plan) => plan.friendId === friend.id).length ? state.planDrafts.filter((plan) => plan.friendId === friend.id).map((plan) => <article className="proposal" key={plan.id}><p>“{plan.message}” <span className="tag">{plan.status}</span></p><div className="button-row"><button className="secondary" onClick={() => copyDraft(plan.message)}>Copy draft message</button><button className="secondary" onClick={() => onPlanOutcome(plan.id, "planned")}>Record planned</button><button className="secondary" onClick={() => onPlanOutcome(plan.id, "met")}>Record met</button><button className="secondary" onClick={() => onPlanOutcome(plan.id, "not-now")}>Record not now</button></div></article>) : <p className="empty">No outcome has been recorded. Circle never assumes attendance.</p>}{copyStatus && <p className="quiet" role="status">{copyStatus}</p>}</section></>}</>;
}

function toActivity(event: PublicEvent): Omit<Activity, "id" | "retrievedAt"> { return { title: event.title, details: event.description, location: event.location, startsAt: event.startsAt, source: "public-events", sourceUrl: event.url, tags: event.tags ?? [] }; }
function dateAfterDays(days: number) { return new Date(Date.now() + days * 86_400_000).toISOString(); }
function eventSearchRange() { const from = new Date(); return { from: from.toISOString(), to: new Date(from.getTime() + 30 * 86_400_000).toISOString() }; }
