"use client";

import { useEffect, useRef, useState } from "react";
import { saveAudio } from "@/lib/audio-store";

type SpeechResultEvent = { results: ArrayLike<ArrayLike<{ transcript: string }>> };
type SpeechRecognitionLike = { continuous: boolean; interimResults: boolean; lang: string; start(): void; stop(): void; onresult: ((event: SpeechResultEvent) => void) | null; onerror: (() => void) | null };
type SpeechWindow = Window & typeof globalThis & { SpeechRecognition?: new () => SpeechRecognitionLike; webkitSpeechRecognition?: new () => SpeechRecognitionLike };

export function VoiceCapture({ retention, friendIds, onSaved }: { retention: "transcript-only" | "retain-until-deletion"; friendIds: string[]; onSaved: (input: { text: string; audioId?: string; friendIds: string[] }) => void }) {
  const recorder = useRef<MediaRecorder | null>(null); const recognition = useRef<SpeechRecognitionLike | null>(null); const stream = useRef<MediaStream | null>(null); const chunks = useRef<Blob[]>([]); const capturedText = useRef("");
  const [state, setState] = useState<"idle" | "recording" | "ready">("idle"); const [audio, setAudio] = useState<Blob | null>(null); const [transcript, setTranscript] = useState(""); const [message, setMessage] = useState("");
  useEffect(() => () => { stream.current?.getTracks().forEach((track) => track.stop()); recognition.current?.stop(); }, []);
  const start = async () => { try { if (!navigator.mediaDevices?.getUserMedia || !window.MediaRecorder) throw new Error("This browser does not support microphone recording."); stream.current = await navigator.mediaDevices.getUserMedia({ audio: true }); chunks.current = []; capturedText.current = ""; setTranscript(""); const next = new MediaRecorder(stream.current); recorder.current = next; next.ondataavailable = (event) => { if (event.data.size) chunks.current.push(event.data); }; next.onstop = () => { stream.current?.getTracks().forEach((track) => track.stop()); setAudio(new Blob(chunks.current, { type: next.mimeType || "audio/webm" })); setState("ready"); setMessage(capturedText.current ? "Your spoken context is ready to keep." : "No words were transcribed. Try again in a browser with speech recognition enabled."); }; next.start(); const Recognition = (window as SpeechWindow).SpeechRecognition ?? (window as SpeechWindow).webkitSpeechRecognition; if (Recognition) { const listener = new Recognition(); recognition.current = listener; listener.continuous = true; listener.interimResults = false; listener.lang = navigator.language; listener.onresult = (event) => { const text = Array.from(event.results).map((result) => result[0]?.transcript ?? "").join(" ").trim(); capturedText.current = text; setTranscript(text); }; listener.onerror = () => setMessage("Your recording stays here, but this browser could not turn speech into text."); listener.start(); setMessage("Listening. Speak naturally, then tap stop."); } else setMessage("Listening. This browser does not provide speech recognition, so context cannot be saved without a transcription engine."); setState("recording"); } catch { setMessage("Microphone access was not granted. You can return whenever you are ready."); } };
  const stop = () => { if (recorder.current?.state === "recording") recorder.current.stop(); recognition.current?.stop(); };
  const save = async () => { if (!transcript.trim()) { setMessage("A transcript is needed to preserve context. Try recording again with speech recognition enabled."); return; } try { let audioId: string | undefined; if (audio && retention === "retain-until-deletion") { audioId = `audio-${crypto.randomUUID()}`; await saveAudio(audioId, audio); } onSaved({ text: transcript, audioId, friendIds }); setAudio(null); setTranscript(""); setState("idle"); setMessage(audioId ? "Voice context saved privately." : "Spoken context saved. Audio was not retained."); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not save your spoken context."); } };
  return <section className="voice-capture" aria-label="Add a voice note">{state === "recording" ? <button className="voice-button listening" onClick={stop} aria-label="Stop recording"><MicIcon /><span className="record-pulse" aria-hidden="true" /></button> : state === "ready" ? <><button className="voice-button save-voice" onClick={save}>Save note</button>{transcript && <p className="spoken-preview">“{transcript}”</p>}</> : <button className="voice-button" onClick={start} aria-label="Record a voice note"><MicIcon /></button>}{message && <p className="voice-status" role="status">{message}</p>}</section>;
}

function MicIcon() { return <svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><rect x="8" y="3" width="8" height="12" rx="4" /><path d="M5.5 11.5a6.5 6.5 0 0 0 13 0M12 18v3M8.5 21h7" /></svg>; }
