"use client";

import { useEffect, useRef, useState } from "react";
import { saveAudio } from "@/lib/audio-store";

export function VoiceCapture({ retention, onSaved }: { retention: "transcript-only" | "retain-until-deletion"; onSaved: (input: { text: string; audioId?: string }) => void }) {
  const recorder = useRef<MediaRecorder | null>(null); const stream = useRef<MediaStream | null>(null); const chunks = useRef<Blob[]>([]); const [state, setState] = useState<"idle" | "recording" | "ready">("idle"); const [audio, setAudio] = useState<Blob | null>(null); const [url, setUrl] = useState(""); const [transcript, setTranscript] = useState(""); const [message, setMessage] = useState("Voice is optional. Text capture always works.");
  useEffect(() => () => { stream.current?.getTracks().forEach((track) => track.stop()); if (url) URL.revokeObjectURL(url); }, [url]);
  useEffect(() => { const interrupt = () => { if (document.visibilityState === "hidden" && recorder.current?.state === "recording") { recorder.current.stop(); setMessage("Recording stopped when the app moved to the background. Review playback before saving."); } }; document.addEventListener("visibilitychange", interrupt); return () => document.removeEventListener("visibilitychange", interrupt); }, []);
  const start = async () => { try { if (!navigator.mediaDevices?.getUserMedia || !window.MediaRecorder) throw new Error("This browser does not support microphone recording."); stream.current = await navigator.mediaDevices.getUserMedia({ audio: true }); chunks.current = []; const next = new MediaRecorder(stream.current); recorder.current = next; next.ondataavailable = (event) => { if (event.data.size) chunks.current.push(event.data); }; next.onstop = () => { stream.current?.getTracks().forEach((track) => track.stop()); const recording = new Blob(chunks.current, { type: next.mimeType || "audio/webm" }); setAudio(recording); setUrl(URL.createObjectURL(recording)); setState("ready"); if (!message.startsWith("Recording stopped")) setMessage("Recording ready. Add or edit the transcript before saving."); }; next.start(); setState("recording"); setMessage("Recording locally. Stop when you are done."); } catch { setMessage("Microphone is unavailable or permission was not granted. Use text instead."); } };
  const stop = () => recorder.current?.state === "recording" && recorder.current.stop();
  const save = async () => { if (!transcript.trim()) { setMessage("Add a transcript or use the text form below. No remote transcription is active."); return; } try { let audioId: string | undefined; if (audio && retention === "retain-until-deletion") { audioId = `audio-${crypto.randomUUID()}`; await saveAudio(audioId, audio); } onSaved({ text: transcript, audioId }); setAudio(null); setTranscript(""); setState("idle"); setMessage(audioId ? "Voice note and editable transcript saved locally." : "Editable transcript saved. Audio was not retained."); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not retain audio locally. The text transcript is still available to save."); } };
  return <section className="voice-panel" aria-labelledby="voice-heading"><div><p className="eyebrow">Voice capture, optional</p><h2 id="voice-heading">Record locally, then edit the words.</h2><p className="quiet">On-device transcription is not enabled because no approach has passed the privacy and reliability feasibility gate. This recording is never uploaded.</p></div>{state === "recording" ? <button className="danger" onClick={stop}>Stop recording</button> : <button className="secondary" onClick={start}>{state === "ready" ? "Record again" : "Start recording"}</button>}<p className="voice-status" role="status">{message}</p>{url && <audio controls src={url}>Your browser cannot play this recording.</audio>}{state === "ready" && <><label>Editable transcript<textarea rows={4} value={transcript} onChange={(event) => setTranscript(event.target.value)} placeholder="Write what you said, or the parts you want to keep."/></label><button className="primary" onClick={save}>Save voice note locally</button></>}</section>;
}
