"use client";

import { useEffect, useRef, useState } from "react";
import { clearAudio } from "@/lib/audio-store";
import { extractFixtureProposals } from "@/lib/extraction";
import { getFixturePhotoLibraryScan, getFixtureWorkspace } from "@/lib/fixtures";
import { LocalWorkspaceRepository, type WorkspaceState } from "@/lib/workspace";
import { ExtractionReview } from "@/components/extraction-review";
import { Planning } from "@/components/planning";
import { VoiceCapture } from "@/components/voice-capture";
import { EventFeed } from "@/components/event-feed";
import { PhotoLibrary } from "@/components/photo-library";

type View = "today" | "moment" | "people" | "settings" | "review" | "plan";

export function WorkspaceApp() {
  const repo = useRef<LocalWorkspaceRepository | null>(null);
  const [state, setState] = useState<WorkspaceState | null>(null);
  const [view, setView] = useState<View>("today");
  const [message, setMessage] = useState("");
  useEffect(() => { repo.current = new LocalWorkspaceRepository(window.localStorage); const current = repo.current.load(); const refreshFixture = current.fixtureMode && (current.friends.length !== 8 || current.activities.length < 18 || current.friends[0]?.id !== "priya-shah"); setState(!current.circle || refreshFixture ? repo.current.seed(getFixtureWorkspace()) : current); }, []);
  const mutate = (action: (repository: LocalWorkspaceRepository) => WorkspaceState, nextMessage = "Saved privately on this device.") => { try { const next = action(repo.current!); setState(next); setMessage(nextMessage); } catch (error) { setMessage(error instanceof Error ? error.message : "Something could not be saved."); } };
  const resetWorkspace = async (fixture?: boolean) => { try { await clearAudio(); mutate((repository) => fixture ? repository.seed(getFixtureWorkspace()) : repository.reset(), fixture ? "Synthetic Circle reset." : "Your local Circle was deleted."); setView("today"); } catch { setMessage("The workspace was not reset because retained audio could not be cleared."); } };
  const extractNote = (noteId: string) => mutate((repository) => { const current = repository.load(); const note = current.notes.find((item) => item.id === noteId); if (!note) throw new Error("The source note no longer exists."); const proposals = extractFixtureProposals(note, current.friends); if (!proposals.length) throw new Error("No grounded proposal was found. Clarify the person or add text instead."); let next = current; for (const proposal of proposals) next = repository.addFactProposal(proposal); return next; }, "Circle added reviewable suggestions. Nothing became memory yet.");
  const friendName = (id: string) => state?.friends.find((friend) => friend.id === id)?.displayName ?? "Deleted friend";

  if (!state) return <main className="workspace-loading"><p>Opening your private Circle…</p></main>;

  return <main className="circle-shell">
    <div className="ambient ambient-lilac" aria-hidden="true" /><div className="ambient ambient-mint" aria-hidden="true" />
    <header className="circle-topbar"><button className="wordmark" onClick={() => setView("today")}>circle<span>.</span></button></header>
    {message && <p className="sr-only" role="status">{message}</p>}
    {!state.circle ? <SetupCircle onCreate={(input) => mutate((repository) => repository.createCircle(input), "Your private Circle is ready.")} onFixture={() => resetWorkspace(true)} /> : <>
      <section className="circle-content">
        {view === "today" && <Today state={state} onAddMoment={() => setView("moment")} onPlan={() => setView("plan")} onPeople={() => setView("people")} />}
        {view === "moment" && <AddMoment state={state} friendName={friendName} onScan={() => mutate((repository) => repository.scanPhotoLibrary(getFixturePhotoLibraryScan(state.friends)), "Circle scanned your photos and found new moments.")} onSaveNote={(input) => mutate((repository) => repository.createNote(input))} />}
        {view === "people" && <People state={state} onPlan={() => setView("plan")} onAddressUpdate={(id, address) => mutate((repository) => repository.updateFriendAddress(id, address), "Address saved privately on this device.")} />}
        {view === "settings" && <Settings state={state} onBack={() => setView("today")} onReview={() => setView("review")} onFixture={() => resetWorkspace(true)} onReset={() => resetWorkspace()} onExport={() => downloadExport(repo.current!.export())} />}
        {view === "review" && <section className="contextual-page"><BackButton onClick={() => setView("settings")} label="Back to settings" /><ExtractionReview state={state} onExtract={extractNote} onApprove={(id) => mutate((repository) => repository.approveProposal(id), "Memory saved with its source note.")} onReject={(id) => mutate((repository) => repository.rejectProposal(id), "Suggestion rejected. Nothing was saved.")} onDeleteProposal={(id) => mutate((repository) => repository.deleteProposal(id), "Suggestion deleted.")} onEditMemory={(id, value) => mutate((repository) => repository.editMemory(id, value), "Memory updated.")} onForgetMemory={(id) => mutate((repository) => repository.forgetMemory(id), "Memory forgotten.")} onMergeMemories={(primary, duplicate) => mutate((repository) => repository.mergeMemories(primary, duplicate), "Memories merged.")} /></section>}
        {view === "plan" && <section className="contextual-page"><BackButton onClick={() => setView("today")} label="Back to Today" /><Planning state={state} onPrompt={(friendId, input) => mutate((repository) => repository.setPrompt(friendId, input))} onPromptEnabled={(friendId, enabled) => mutate((repository) => repository.setPromptEnabled(friendId, enabled))} onAddActivity={(input) => mutate((repository) => repository.addActivity(input))} onCreatePlan={(input) => mutate((repository) => repository.createPlan(input))} onPlanOutcome={(planId, status) => mutate((repository) => repository.recordPlanOutcome(planId, status))} /></section>}
      </section>
      {(["today", "moment", "people"] as View[]).includes(view) && <nav className="circle-nav" aria-label="Circle"><NavButton current={view} target="today" label="Plan" icon="home" onClick={setView} /><NavButton current={view} target="moment" label="Capture" icon="spark" onClick={setView} /><NavButton current={view} target="people" label="People" icon="people" onClick={setView} /></nav>}
    </>}
  </main>;
}

function NavButton({ current, target, label, icon, onClick }: { current: View; target: View; label: string; icon: IconName; onClick: (view: View) => void }) { return <button className={current === target ? "nav-button selected" : "nav-button"} onClick={() => onClick(target)} aria-current={current === target ? "page" : undefined}><Icon name={icon} /><span>{label}</span></button>; }
function BackButton({ onClick, label }: { onClick: () => void; label: string }) { return <button className="back-button" onClick={onClick}><Icon name="arrow-left" /> {label}</button>; }

function SetupCircle({ onCreate, onFixture }: { onCreate: (input: { name: string; city: string }) => void; onFixture: () => void }) { const [city, setCity] = useState(""); return <section className="setup"><div className="setup-orb" aria-hidden="true"><Icon name="spark" /></div><p className="eyebrow">Private by default</p><h1>Make room for the people you love.</h1><p className="lede">A quieter place for the details that make seeing someone again feel easy.</p><form className="form-stack" onSubmit={(event) => { event.preventDefault(); onCreate({ name: "My people", city }); }}><label>Your city, optional<input value={city} onChange={(event) => setCity(event.target.value)} placeholder="Sydney" /></label><button className="primary" type="submit">Begin privately <Icon name="arrow-right" /></button></form><button className="text-button" onClick={onFixture}>Explore a sample space</button><p className="quiet">No account, contact import, or network connection is needed.</p></section>; }

function Today({ state, onPlan }: { state: WorkspaceState; onAddMoment: () => void; onPlan: () => void; onPeople: () => void }) { return <EventFeed state={state} onPlan={onPlan} />; }

function AddMoment({ state, friendName, onScan, onSaveNote }: { state: WorkspaceState; friendName: (id: string) => string; onScan: () => void; onSaveNote: (input: { text: string; friendIds: string[]; audioId?: string }) => void }) {
  return <section className="moment-screen capture-screen"><section className="page-heading compact-heading"><h1>Hangouts</h1></section><PhotoLibrary state={state} friendName={friendName} onScan={onScan} /><VoiceCapture retention={state.privacySettings.audioRetention} friendIds={[]} onSaved={({ text: voiceText, audioId, friendIds }) => onSaveNote({ text: voiceText, friendIds, audioId })} /></section>;
}

function People({ state, onPlan, onAddressUpdate }: { state: WorkspaceState; onPlan: () => void; onAddressUpdate: (id: string, address: string) => void }) {
  const activeFriends = state.friends.filter((friend) => !friend.archived); const [selectedId, setSelectedId] = useState<string | null>(null); const selected = activeFriends.find((friend) => friend.id === selectedId);
  if (selected) { const shared = activeFriends.filter((friend) => friend.id !== selected.id).slice(0, 6); return <section className="contact-card"><button className="contact-back" onClick={() => setSelectedId(null)} aria-label="Back to people"><Icon name="arrow-left" /></button><div className="contact-orb" style={{ backgroundImage: `url(${personImage(selected.id)})` }} aria-label={`${selected.displayName}'s photo`} /><h1>{firstName(selected.displayName)}</h1><label className="address-field">Address<input value={selected.address ?? ""} onChange={(event) => onAddressUpdate(selected.id, event.target.value)} placeholder="Suburb or address" /></label><div className="contact-actions"><button type="button">✦<span>Nudge</span></button><button type="button">◌<span>Note</span></button><button onClick={onPlan}>↗<span>Plan</span></button></div><section><h2>Shared people</h2><div className="mutual-row">{shared.map((friend) => <span key={friend.id}>{initials(friend.displayName)}</span>)}</div></section><section><h2>Shared events</h2><div className="shared-events">{state.activities.slice(0, 2).map((activity, index) => <article key={activity.id}><span className={`shared-event-art theme-${index + 2}`} /><strong>{activity.title}</strong><small>{activity.details}</small></article>)}</div></section></section>; }
  return <section className="people-screen"><header><p>People</p><h1>Your circle</h1><small>Faces, not follower counts.</small></header><div className="people-mosaic">{activeFriends.map((friend, index) => <button className="mosaic-person" key={friend.id} style={{ "--i": index } as React.CSSProperties} onClick={() => setSelectedId(friend.id)}><span className="mosaic-photo" style={{ backgroundImage: `url(${personImage(friend.id)})` }}><span className="mosaic-badge">{initials(friend.displayName)}</span></span><strong>{firstName(friend.displayName)}</strong><small>{state.memoryFacts.find((fact) => fact.friendId === friend.id)?.value}</small></button>)}</div></section>;
}

function Settings({ state, onBack, onReview, onFixture, onReset, onExport }: { state: WorkspaceState; onBack: () => void; onReview: () => void; onFixture: () => void; onReset: () => void; onExport: () => void }) { return <section className="settings-page"><BackButton onClick={onBack} label="Back to Today" /><p className="eyebrow">Settings</p><h1>Your data stays yours.</h1><p className="lede">Review, export, or delete your private Circle whenever you need to.</p><section className="settings-actions"><button className="secondary" onClick={onReview}>Review saved context</button><button className="secondary" onClick={onExport}>Export local data</button><button className="secondary" onClick={onFixture}>Reset to the synthetic demo</button><button className="danger" onClick={() => { if (window.confirm("Delete this entire local Circle? This cannot be undone.")) onReset(); }}>Delete this Circle</button></section><section className="privacy-note"><p className="eyebrow">What Circle can access</p><h2>Only what you choose to add.</h2><p>No account, contact import, background listening, photo-library access, or remote processor is active in this build.</p></section><details className="recovery-details"><summary>Inspect local records</summary><p className="quiet">{state.fixtureMode ? "Synthetic demo workspace" : "Local workspace"}: {state.friends.length} people, {state.notes.length} notes, {state.momentCandidates.length} moment candidates, and {state.confirmedHangouts.length} confirmed moments.</p><pre>{JSON.stringify(state, null, 2)}</pre></details></section>; }

function firstName(name: string) { return name.split(" ")[0] ?? name; }
function initials(name: string) { return name.split(" ").map((part) => part[0]).join("").slice(0, 2); }
function personImage(id: string) { const images: Record<string, string> = { "priya-shah": "/friends/priya-shah.jpeg", "hana-kim": "/friends/hana-kim.jpeg", "arjun-patel": "/friends/arjun-patel.jpeg", "rohan-mehta": "/friends/rohan-mehta.jpeg", "isla-morgan": "/friends/isla-morgan.jpeg", "haru-sato": "/friends/haru-sato.jpeg", "tyler-woodward": "/friends/tyler-woodward.jpeg", "yingying-zhang": "/friends/yingying-zhang.jpeg" }; return images[id] ?? "/friends/priya-shah.jpeg"; }
function downloadExport(content: string) { const blob = new Blob([content], { type: "application/json" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "circle-local-export.json"; anchor.click(); URL.revokeObjectURL(url); }

type IconName = "arrow-left" | "arrow-right" | "chevron-right" | "home" | "people" | "plus" | "settings" | "spark" | "wave";
function Icon({ name }: { name: IconName }) { const paths: Record<IconName, React.ReactNode> = { "arrow-left": <path d="m14 6-6 6 6 6M8 12h10" />, "arrow-right": <path d="m10 6 6 6-6 6M16 12H6" />, "chevron-right": <path d="m9 6 6 6-6 6" />, home: <><path d="m4 10 8-6 8 6v8a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2z" /><path d="M9 20v-6h6v6" /></>, people: <><circle cx="9" cy="8" r="3" /><path d="M3.5 20c.7-3.2 2.5-5 5.5-5s4.8 1.8 5.5 5M16 5.5a3 3 0 0 1 0 5.7M17.5 15.4c1.6.6 2.7 2.1 3 4.6" /></>, plus: <path d="M12 5v14M5 12h14" />, settings: <><circle cx="12" cy="12" r="3" /><path d="M19.4 15a1.7 1.7 0 0 0 .3 1.9l.1.1-2.2 2.2-.1-.1a1.7 1.7 0 0 0-1.9-.3 1.7 1.7 0 0 0-1 1.5v.2h-3.2v-.2a1.7 1.7 0 0 0-1-1.5 1.7 1.7 0 0 0-1.9.3l-.1.1-2.2-2.2.1-.1A1.7 1.7 0 0 0 6.6 15a1.7 1.7 0 0 0-1.5-1H5v-3.2h.1a1.7 1.7 0 0 0 1.5-1 1.7 1.7 0 0 0-.3-1.9l-.1-.1 2.2-2.2.1.1a1.7 1.7 0 0 0 1.9.3 1.7 1.7 0 0 0 1-1.5V4h3.2v.2a1.7 1.7 0 0 0 1 1.5 1.7 1.7 0 0 0 1.9-.3l.1-.1 2.2 2.2-.1.1a1.7 1.7 0 0 0-.3 1.9 1.7 1.7 0 0 0 1.5 1h.2V14h-.2a1.7 1.7 0 0 0-1.4 1Z" /></>, spark: <path d="m12 3 1.7 5.3L19 10l-5.3 1.7L12 17l-1.7-5.3L5 10l5.3-1.7z" />, wave: <path d="M4 15c2.1 0 2.1-6 4.2-6s2.1 6 4.2 6 2.1-6 4.2-6 2.1 6 3.4 6" /> };
  return <svg className={`icon icon-${name}`} viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{paths[name]}</svg>;
}
