import { z } from "zod";
import type { FactProposal, Friend, Note } from "@/lib/workspace";

export const proposalSchema = z.object({ friendId: z.string().min(1), sourceNoteId: z.string().min(1), type: z.enum(["shared-interest", "preference", "intention"]), value: z.string().min(1).max(240), temporalQualifier: z.string().max(120).optional(), sourceSpan: z.object({ start: z.number().int().nonnegative(), end: z.number().int().nonnegative(), text: z.string().min(1) }).refine((span) => span.end > span.start), confidence: z.number().min(0).max(1), suggestedIntent: z.enum(["remember", "plan"]), adapter: z.literal("fixture-extractor-v1") });
export type ProposedFactInput = z.infer<typeof proposalSchema>;
export interface ExtractionAdapter { name: ProposedFactInput["adapter"]; extract(note: Note, friends: Friend[]): ProposedFactInput[]; }
export type Resolution = { kind: "resolved"; friendId: string } | { kind: "ambiguous"; friendIds: string[] } | { kind: "none" };

export function resolveFriendReference(text: string, friends: Friend[]): Resolution { const matches = friends.filter((friend) => { const names = friend.displayName.toLowerCase().split(/\s+/); const lower = text.toLowerCase(); return lower.includes(friend.displayName.toLowerCase()) || (names[0].length > 2 && new RegExp(`\\b${escapeRegex(names[0])}\\b`, "i").test(text)); }); return matches.length === 1 ? { kind: "resolved", friendId: matches[0].id } : matches.length > 1 ? { kind: "ambiguous", friendIds: matches.map((friend) => friend.id) } : { kind: "none" }; }
export function extractFixtureProposals(note: Note, friends: Friend[]): ProposedFactInput[] { const resolution = resolveFriendReference(note.text, friends); if (resolution.kind !== "resolved") return []; const patterns: Array<{ regex: RegExp; type: ProposedFactInput["type"]; intent: ProposedFactInput["suggestedIntent"] }> = [{ regex: /(?:loves|likes|enjoys|misses) ([^.!,;]+)/i, type: "preference", intent: "remember" }, { regex: /(?:should|want to|we could) ([^.!,;]+)/i, type: "intention", intent: "plan" }]; return patterns.flatMap(({ regex, type, intent }) => { const match = regex.exec(note.text); if (!match?.[1]) return []; const value = match[1].trim(); const start = (match.index ?? 0) + match[0].indexOf(match[1]); return [proposalSchema.parse({ friendId: resolution.friendId, sourceNoteId: note.id, type, value, sourceSpan: { start, end: start + value.length, text: value }, confidence: 0.62, suggestedIntent: intent, adapter: "fixture-extractor-v1" })]; }); }
export function validateProposalAgainstNote(proposal: ProposedFactInput, note: Note): boolean { return proposal.sourceNoteId === note.id && note.text.slice(proposal.sourceSpan.start, proposal.sourceSpan.end) === proposal.sourceSpan.text; }
export const fixtureExtractionAdapter: ExtractionAdapter = { name: "fixture-extractor-v1", extract: extractFixtureProposals };
const escapeRegex = (value: string) => value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
export const toProposalRecord = (input: ProposedFactInput): Omit<FactProposal, "id" | "status" | "createdAt"> => input;
