export const CURRENT_SCHEMA_VERSION = 9;
export const BETA_ACTIVE_FRIEND_LIMIT = 10;
export const LOCAL_WORKSPACE_KEY = "innercircle.workspace";

export type Id = string;
export type Friend = { id: Id; displayName: string; address?: string; cadenceDays: number; promptEnabled: boolean; archived: boolean; createdAt: string };
export type Note = { id: Id; text: string; capturedAt: string; friendIds: Id[]; state: "saved"; audioId?: Id; transcriptionMode: "manual-text" | "remote-opt-in" };
export type Interaction = { id: Id; friendId: Id; kind: "in-person" | "remote"; occurredAt: string; note?: string };
export type PhotoAnalysisKind = "fixture" | "metadata" | "on-device-recognition" | "user-selection";
export type PhotoMetadata = { assetId: Id; label: string; caption?: string; capturedAt?: string; place?: string; retention: "not-stored" | "local-reference"; src?: string };
export type MomentCandidate = { id: Id; photo: PhotoMetadata; candidateFriendIds: Id[]; analysisKind: PhotoAnalysisKind; analysisLabel: string; status: "pending" | "dismissed" | "confirmed"; createdAt: string; updatedAt: string; factProposalIds?: Id[] };
export type PhotoLibraryEntry = { photo: Omit<PhotoMetadata, "retention"> & { retention?: PhotoMetadata["retention"] }; candidateFriendIds: Id[]; noteText: string; fact: { type: FactProposal["type"]; value: string } };
export type ConfirmedHangout = { id: Id; momentCandidateId?: Id; friendIds: Id[]; occurredAt: string; place?: string; confirmedAt: string };
export type FactProposal = { id: Id; friendId: Id; sourceNoteId: Id; type: "shared-interest" | "preference" | "intention"; value: string; temporalQualifier?: string; sourceSpan: { start: number; end: number; text: string }; confidence: number; suggestedIntent: "remember" | "plan"; adapter: "fixture-extractor-v1"; status: "pending" | "rejected" | "approved"; createdAt: string };
export type MemoryFact = { id: Id; friendId: Id; sourceNoteId: Id; proposalId: Id; type: string; value: string; approvedAt: string; adapter: FactProposal["adapter"]; confidence: number; editHistory: string[] };
export type Activity = { id: Id; title: string; details?: string; location?: string; startsAt?: string; source: "manual" | "fixture" | "public-events"; sourceUrl?: string; retrievedAt: string; tags: string[] };
export type Prompt = { id: Id; friendId: Id; reason: string; state: "active" | "snoozed" | "dismissed"; snoozedUntil?: string; generatedAt: string; updatedAt: string };
export type PlanDraft = { id: Id; friendId: Id; activityId?: Id; message: string; status: "draft" | "planned" | "met" | "not-now"; createdAt: string; outcomeRecordedAt?: string };
export type PrivacySettings = { audioRetention: "transcript-only" | "retain-until-deletion"; telemetryOptIn: boolean; remoteProcessingDefault: "ask-every-note"; updatedAt: string };
export type PhotoLibraryStatus = { granted: boolean; grantedAt?: string; lastScannedAt?: string };
export type PhotoStar = { photoId: Id; starredAt: string };
export type WorkspaceState = {
  schemaVersion: number; fixtureMode: boolean; city: string; circle: { id: Id; name: string; maxMembers: number } | null; friends: Friend[]; notes: Note[]; interactions: Interaction[]; momentCandidates: MomentCandidate[]; confirmedHangouts: ConfirmedHangout[]; factProposals: FactProposal[]; memoryFacts: MemoryFact[]; activities: Activity[]; prompts: Prompt[]; planDrafts: PlanDraft[]; privacySettings: PrivacySettings; photoLibrary: PhotoLibraryStatus; photoStars: PhotoStar[]; migrationHistory: Array<{ version: number; migratedAt: string }>;
};
export type StorageLike = Pick<Storage, "getItem" | "setItem" | "removeItem">;
const now = () => new Date().toISOString();
const makeId = (prefix: string) => `${prefix}-${globalThis.crypto?.randomUUID?.() ?? `${Date.now()}-${Math.random().toString(36).slice(2)}`}`;

export function emptyWorkspace(): WorkspaceState {
  const createdAt = now();
  return { schemaVersion: CURRENT_SCHEMA_VERSION, fixtureMode: false, city: "", circle: null, friends: [], notes: [], interactions: [], momentCandidates: [], confirmedHangouts: [], factProposals: [], memoryFacts: [], activities: [], prompts: [], planDrafts: [], privacySettings: { audioRetention: "transcript-only", telemetryOptIn: false, remoteProcessingDefault: "ask-every-note", updatedAt: createdAt }, photoLibrary: { granted: false }, photoStars: [], migrationHistory: [{ version: CURRENT_SCHEMA_VERSION, migratedAt: createdAt }] };
}
export function migrateWorkspace(input: unknown): WorkspaceState {
  if (!input || typeof input !== "object") return emptyWorkspace();
  let value = input as Partial<WorkspaceState>;
  if ((value.schemaVersion ?? 0) > CURRENT_SCHEMA_VERSION) return emptyWorkspace();
  while ((value.schemaVersion ?? 0) < CURRENT_SCHEMA_VERSION) {
    if ((value.schemaVersion ?? 0) === 0) value = migrateV0ToV1(value);
    else if (value.schemaVersion === 1) value = migrateV1ToV2(value);
    else if (value.schemaVersion === 2) value = migrateV2ToV3(value);
    else if (value.schemaVersion === 3) value = migrateV3ToV4(value);
    else if (value.schemaVersion === 4) value = migrateV4ToV5(value);
    else if (value.schemaVersion === 5) value = migrateV5ToV6(value);
    else if (value.schemaVersion === 6) value = migrateV6ToV7(value);
    else if (value.schemaVersion === 7) value = migrateV7ToV8(value);
    else if (value.schemaVersion === 8) value = migrateV8ToV9(value);
    else return emptyWorkspace();
  }
  const base = emptyWorkspace();
  return { ...base, ...value, circle: value.circle ?? null, friends: value.friends ?? [], notes: value.notes ?? [], interactions: value.interactions ?? [], momentCandidates: value.momentCandidates ?? [], confirmedHangouts: value.confirmedHangouts ?? [], factProposals: value.factProposals ?? [], memoryFacts: value.memoryFacts ?? [], activities: value.activities ?? [], prompts: value.prompts ?? [], planDrafts: value.planDrafts ?? [], privacySettings: { ...base.privacySettings, ...value.privacySettings }, photoLibrary: { ...base.photoLibrary, ...value.photoLibrary }, photoStars: value.photoStars ?? [], migrationHistory: value.migrationHistory?.length ? value.migrationHistory : base.migrationHistory };
}
function migrateV0ToV1(value: Partial<WorkspaceState>): Partial<WorkspaceState> { return { ...value, schemaVersion: 1, migrationHistory: [...(value.migrationHistory ?? []), { version: 1, migratedAt: now() }] }; }
function migrateV1ToV2(value: Partial<WorkspaceState>): Partial<WorkspaceState> { return { ...value, schemaVersion: 2, notes: value.notes?.map((note) => ({ ...note, transcriptionMode: "manual-text" })) ?? [], migrationHistory: [...(value.migrationHistory ?? []), { version: 2, migratedAt: now() }] }; }
function migrateV2ToV3(value: Partial<WorkspaceState>): Partial<WorkspaceState> { return { ...value, schemaVersion: 3, factProposals: value.factProposals?.map((proposal) => ({ ...proposal, type: proposal.type === "shared-interest" || proposal.type === "preference" || proposal.type === "intention" ? proposal.type : "preference", sourceSpan: { start: 0, end: proposal.value.length, text: proposal.value }, suggestedIntent: "remember", adapter: "fixture-extractor-v1" })) ?? [], migrationHistory: [...(value.migrationHistory ?? []), { version: 3, migratedAt: now() }] }; }
function migrateV3ToV4(value: Partial<WorkspaceState>): Partial<WorkspaceState> { return { ...value, schemaVersion: 4, memoryFacts: value.memoryFacts?.map((memory) => ({ ...memory, proposalId: memory.sourceNoteId, adapter: "fixture-extractor-v1", confidence: 0 })) ?? [], migrationHistory: [...(value.migrationHistory ?? []), { version: 4, migratedAt: now() }] }; }
function migrateV4ToV5(value: Partial<WorkspaceState>): Partial<WorkspaceState> { return { ...value, schemaVersion: 5, friends: value.friends?.map((friend) => ({ ...friend, promptEnabled: true })) ?? [], prompts: value.prompts?.map((prompt) => ({ ...prompt, updatedAt: prompt.generatedAt })) ?? [], migrationHistory: [...(value.migrationHistory ?? []), { version: 5, migratedAt: now() }] }; }
function migrateV5ToV6(value: Partial<WorkspaceState>): Partial<WorkspaceState> { return { ...value, schemaVersion: 6, momentCandidates: [], confirmedHangouts: [], migrationHistory: [...(value.migrationHistory ?? []), { version: 6, migratedAt: now() }] }; }
function migrateV6ToV7(value: Partial<WorkspaceState>): Partial<WorkspaceState> { return { ...value, schemaVersion: 7, friends: value.friends?.map((friend) => ({ ...friend, address: friend.address ?? "" })) ?? [], migrationHistory: [...(value.migrationHistory ?? []), { version: 7, migratedAt: now() }] }; }
function migrateV7ToV8(value: Partial<WorkspaceState>): Partial<WorkspaceState> { return { ...value, schemaVersion: 8, photoLibrary: value.photoLibrary ?? { granted: false }, migrationHistory: [...(value.migrationHistory ?? []), { version: 8, migratedAt: now() }] }; }
function migrateV8ToV9(value: Partial<WorkspaceState>): Partial<WorkspaceState> { return { ...value, schemaVersion: 9, photoStars: value.photoStars ?? [], migrationHistory: [...(value.migrationHistory ?? []), { version: 9, migratedAt: now() }] }; }
export const activeFriendCount = (state: WorkspaceState) => state.friends.filter((friend) => !friend.archived).length;

export class LocalWorkspaceRepository {
  constructor(private readonly storage: StorageLike, private readonly key = LOCAL_WORKSPACE_KEY) {}
  load(): WorkspaceState { const raw = this.storage.getItem(this.key); if (!raw) return emptyWorkspace(); try { return migrateWorkspace(JSON.parse(raw)); } catch { return emptyWorkspace(); } }
  save(state: WorkspaceState): WorkspaceState { this.storage.setItem(this.key, JSON.stringify(state)); return state; }
  seed(fixture: WorkspaceState): WorkspaceState { return this.save(structuredClone(fixture)); }
  reset(): WorkspaceState { this.storage.removeItem(this.key); return emptyWorkspace(); }
  export(): string { return JSON.stringify(this.load(), null, 2); }
  createCircle(input: { name: string; city: string; maxMembers?: number }): WorkspaceState { const state = this.load(); if (state.circle) throw new Error("A circle already exists."); const maxMembers = Math.min(input.maxMembers ?? BETA_ACTIVE_FRIEND_LIMIT, BETA_ACTIVE_FRIEND_LIMIT); return this.save({ ...state, city: input.city.trim(), circle: { id: makeId("circle"), name: input.name.trim(), maxMembers } }); }
  addFriend(input: { displayName: string; cadenceDays: number }): WorkspaceState { const state = this.load(); if (!state.circle) throw new Error("Create a circle first."); if (activeFriendCount(state) >= state.circle.maxMembers) throw new Error(`This beta circle supports up to ${state.circle.maxMembers} active friends.`); const name = input.displayName.trim(); if (!name) throw new Error("A friend needs a display name."); return this.save({ ...state, friends: [...state.friends, { id: makeId("friend"), displayName: name, cadenceDays: input.cadenceDays, promptEnabled: true, archived: false, createdAt: now() }] }); }
  updateFriendAddress(friendId: Id, address: string): WorkspaceState { const state = this.load(); return this.save({ ...state, friends: state.friends.map((friend) => friend.id === friendId ? { ...friend, address: address.trim() } : friend) }); }
  createNote(input: { text: string; friendIds: Id[]; capturedAt?: string; audioId?: Id; transcriptionMode?: Note["transcriptionMode"] }): WorkspaceState { const state = this.load(); const text = input.text.trim(); if (!text) throw new Error("Write or transcribe a reflection before saving it."); return this.save({ ...state, notes: [{ id: makeId("note"), text, friendIds: input.friendIds, capturedAt: input.capturedAt ?? now(), state: "saved", audioId: input.audioId, transcriptionMode: input.transcriptionMode ?? "manual-text" }, ...state.notes] }); }
  logInteraction(input: { friendId: Id; occurredAt: string; note?: string; kind?: Interaction["kind"] }): WorkspaceState { const state = this.load(); return this.save({ ...state, interactions: [{ id: makeId("interaction"), friendId: input.friendId, kind: input.kind ?? "in-person", occurredAt: input.occurredAt, note: input.note?.trim() }, ...state.interactions] }); }
  createMomentCandidate(input: Omit<MomentCandidate, "id" | "status" | "createdAt" | "updatedAt">): WorkspaceState { const state = this.load(); if (!input.candidateFriendIds.length) throw new Error("Choose at least one person before saving a moment candidate."); if (input.candidateFriendIds.some((friendId) => !state.friends.some((friend) => friend.id === friendId && !friend.archived))) throw new Error("A moment candidate can only include people in your active Circle."); const timestamp = now(); return this.save({ ...state, momentCandidates: [{ ...input, id: makeId("moment"), status: "pending", createdAt: timestamp, updatedAt: timestamp }, ...state.momentCandidates] }); }
  confirmMomentCandidate(candidateId: Id, input?: { friendIds?: Id[]; occurredAt?: string; place?: string }): WorkspaceState { const state = this.load(); const candidate = state.momentCandidates.find((item) => item.id === candidateId); if (!candidate || candidate.status !== "pending") throw new Error("That moment is no longer waiting for confirmation."); const friendIds = input?.friendIds ?? candidate.candidateFriendIds; if (!friendIds.length || friendIds.some((friendId) => !state.friends.some((friend) => friend.id === friendId && !friend.archived))) throw new Error("Confirm the people in your active Circle before saving this moment."); const timestamp = now(); const hangout: ConfirmedHangout = { id: makeId("hangout"), momentCandidateId: candidate.id, friendIds, occurredAt: input?.occurredAt ?? candidate.photo.capturedAt ?? timestamp, place: input?.place?.trim() || candidate.photo.place, confirmedAt: timestamp }; const linkedIds = new Set(candidate.factProposalIds ?? []); const approvedFacts: MemoryFact[] = state.factProposals.filter((proposal) => linkedIds.has(proposal.id) && proposal.status === "pending").map((proposal) => ({ id: makeId("memory"), friendId: proposal.friendId, sourceNoteId: proposal.sourceNoteId, proposalId: proposal.id, type: proposal.type, value: proposal.value, approvedAt: timestamp, adapter: proposal.adapter, confidence: proposal.confidence, editHistory: [] })); return this.save({ ...state, momentCandidates: state.momentCandidates.map((item) => item.id === candidateId ? { ...item, status: "confirmed", updatedAt: timestamp } : item), confirmedHangouts: [hangout, ...state.confirmedHangouts], factProposals: state.factProposals.map((proposal) => linkedIds.has(proposal.id) && proposal.status === "pending" ? { ...proposal, status: "approved" } : proposal), memoryFacts: [...approvedFacts, ...state.memoryFacts] }); }
  dismissMomentCandidate(candidateId: Id): WorkspaceState { const state = this.load(); const candidate = state.momentCandidates.find((item) => item.id === candidateId); if (!candidate || candidate.status !== "pending") return state; const linkedIds = new Set(candidate.factProposalIds ?? []); return this.save({ ...state, momentCandidates: state.momentCandidates.map((item) => item.id === candidateId ? { ...item, status: "dismissed", updatedAt: now() } : item), factProposals: state.factProposals.map((proposal) => linkedIds.has(proposal.id) && proposal.status === "pending" ? { ...proposal, status: "rejected" } : proposal) }); }
  toggleMomentStar(photoId: Id): WorkspaceState { const state = this.load(); if (!state.momentCandidates.some((candidate) => candidate.id === photoId)) throw new Error("That photo is no longer in your Circle."); const isStarred = state.photoStars.some((star) => star.photoId === photoId); return this.save({ ...state, photoStars: isStarred ? state.photoStars.filter((star) => star.photoId !== photoId) : [{ photoId, starredAt: now() }, ...state.photoStars] }); }
  resetReelPreferences(): WorkspaceState { const state = this.load(); return this.save({ ...state, photoStars: [] }); }
  scanPhotoLibrary(entries: PhotoLibraryEntry[]): WorkspaceState { const state = this.load(); const existingAssetIds = new Set(state.momentCandidates.map((candidate) => candidate.photo.assetId)); const fresh = entries.filter((entry) => !existingAssetIds.has(entry.photo.assetId) && entry.candidateFriendIds.length && entry.candidateFriendIds.every((friendId) => state.friends.some((friend) => friend.id === friendId && !friend.archived))); const timestamp = now(); const notes: Note[] = []; const proposals: FactProposal[] = []; const candidates: MomentCandidate[] = []; const hangouts: ConfirmedHangout[] = []; const memories: MemoryFact[] = []; for (const entry of fresh) { const noteId = makeId("note"); notes.push({ id: noteId, text: entry.noteText, capturedAt: entry.photo.capturedAt ?? timestamp, friendIds: entry.candidateFriendIds, state: "saved", transcriptionMode: "manual-text" }); const start = entry.noteText.indexOf(entry.fact.value); const proposalId = makeId("proposal"); proposals.push({ id: proposalId, friendId: entry.candidateFriendIds[0], sourceNoteId: noteId, type: entry.fact.type, value: entry.fact.value, sourceSpan: { start: Math.max(start, 0), end: Math.max(start, 0) + entry.fact.value.length, text: entry.fact.value }, confidence: 0.74, suggestedIntent: entry.fact.type === "intention" ? "plan" : "remember", adapter: "fixture-extractor-v1", status: "approved", createdAt: timestamp }); const candidateId = makeId("moment"); candidates.push({ id: candidateId, photo: { ...entry.photo, retention: entry.photo.retention ?? "not-stored" }, candidateFriendIds: entry.candidateFriendIds, analysisKind: "fixture", analysisLabel: "Synthetic photo-library scan", status: "confirmed", createdAt: timestamp, updatedAt: timestamp, factProposalIds: [proposalId] }); hangouts.push({ id: makeId("hangout"), momentCandidateId: candidateId, friendIds: entry.candidateFriendIds, occurredAt: entry.photo.capturedAt ?? timestamp, place: entry.photo.place, confirmedAt: timestamp }); memories.push({ id: makeId("memory"), friendId: entry.candidateFriendIds[0], sourceNoteId: noteId, proposalId, type: entry.fact.type, value: entry.fact.value, approvedAt: timestamp, adapter: "fixture-extractor-v1", confidence: 0.74, editHistory: [] }); } return this.save({ ...state, notes: [...notes, ...state.notes], factProposals: [...proposals, ...state.factProposals], momentCandidates: [...candidates, ...state.momentCandidates], confirmedHangouts: [...hangouts, ...state.confirmedHangouts], memoryFacts: [...memories, ...state.memoryFacts], photoLibrary: { granted: true, grantedAt: state.photoLibrary.grantedAt ?? timestamp, lastScannedAt: timestamp } }); }
  addFactProposal(input: Omit<FactProposal, "id" | "status" | "createdAt">): WorkspaceState { const state = this.load(); const note = state.notes.find((item) => item.id === input.sourceNoteId); if (!note || !note.friendIds.includes(input.friendId)) throw new Error("A proposal must reference a locally linked source note and friend."); if (note.text.slice(input.sourceSpan.start, input.sourceSpan.end) !== input.sourceSpan.text) throw new Error("A proposal source span must match its source note."); if (state.factProposals.some((item) => item.sourceNoteId === input.sourceNoteId && item.friendId === input.friendId && item.value === input.value && item.status === "pending")) return state; return this.save({ ...state, factProposals: [{ ...input, id: makeId("proposal"), status: "pending", createdAt: now() }, ...state.factProposals] }); }
  approveProposal(proposalId: Id): WorkspaceState { const state = this.load(); const proposal = state.factProposals.find((item) => item.id === proposalId); if (!proposal || proposal.status !== "pending") return state; return this.save({ ...state, factProposals: state.factProposals.map((item) => item.id === proposalId ? { ...item, status: "approved" } : item), memoryFacts: [{ id: makeId("memory"), friendId: proposal.friendId, sourceNoteId: proposal.sourceNoteId, proposalId: proposal.id, type: proposal.type, value: proposal.value, approvedAt: now(), adapter: proposal.adapter, confidence: proposal.confidence, editHistory: [] }, ...state.memoryFacts] }); }
  rejectProposal(proposalId: Id): WorkspaceState { const state = this.load(); return this.save({ ...state, factProposals: state.factProposals.map((item) => item.id === proposalId ? { ...item, status: "rejected" } : item) }); }
  deleteProposal(proposalId: Id): WorkspaceState { const state = this.load(); return this.save({ ...state, factProposals: state.factProposals.filter((item) => item.id !== proposalId) }); }
  editMemory(memoryId: Id, value: string): WorkspaceState { const state = this.load(); const nextValue = value.trim(); if (!nextValue) throw new Error("A memory cannot be empty."); return this.save({ ...state, memoryFacts: state.memoryFacts.map((item) => item.id === memoryId ? { ...item, value: nextValue, editHistory: [...item.editHistory, item.value] } : item) }); }
  forgetMemory(memoryId: Id): WorkspaceState { const state = this.load(); return this.save({ ...state, memoryFacts: state.memoryFacts.filter((item) => item.id !== memoryId) }); }
  mergeMemories(primaryId: Id, duplicateId: Id): WorkspaceState { const state = this.load(); const primary = state.memoryFacts.find((item) => item.id === primaryId); const duplicate = state.memoryFacts.find((item) => item.id === duplicateId); if (!primary || !duplicate || primary.friendId !== duplicate.friendId || primaryId === duplicateId) throw new Error("Choose two memories for the same friend to merge."); return this.save({ ...state, memoryFacts: state.memoryFacts.filter((item) => item.id !== duplicateId).map((item) => item.id === primaryId ? { ...item, editHistory: [...item.editHistory, duplicate.value, ...duplicate.editHistory] } : item) }); }
  setPromptEnabled(friendId: Id, promptEnabled: boolean): WorkspaceState { const state = this.load(); return this.save({ ...state, friends: state.friends.map((friend) => friend.id === friendId ? { ...friend, promptEnabled } : friend) }); }
  setPrompt(friendId: Id, input: { state: Prompt["state"]; reason: string; snoozedUntil?: string }): WorkspaceState { const state = this.load(); const active = state.prompts.find((prompt) => prompt.friendId === friendId); const timestamp = now(); const prompt = { id: active?.id ?? makeId("prompt"), friendId, reason: input.reason, state: input.state, snoozedUntil: input.snoozedUntil, generatedAt: active?.generatedAt ?? timestamp, updatedAt: timestamp }; return this.save({ ...state, prompts: [prompt, ...state.prompts.filter((item) => item.friendId !== friendId)] }); }
  addActivity(input: { title: string; details?: string; location?: string; startsAt?: string; tags?: string[]; source?: Activity["source"]; sourceUrl?: string }): WorkspaceState { const state = this.load(); const title = input.title.trim(); if (!title) throw new Error("An activity needs a title."); return this.save({ ...state, activities: [{ id: makeId("activity"), title, details: input.details?.trim(), location: input.location?.trim() || undefined, startsAt: input.startsAt, tags: input.tags ?? [], source: input.source ?? "manual", sourceUrl: input.sourceUrl, retrievedAt: now() }, ...state.activities] }); }
  createPlan(input: { friendId: Id; activityId?: Id; message: string }): WorkspaceState { const state = this.load(); const message = input.message.trim(); if (!message) throw new Error("A plan draft needs a message."); return this.save({ ...state, planDrafts: [{ id: makeId("plan"), friendId: input.friendId, activityId: input.activityId, message, status: "draft", createdAt: now() }, ...state.planDrafts] }); }
  recordPlanOutcome(planId: Id, status: Exclude<PlanDraft["status"], "draft">): WorkspaceState { const state = this.load(); return this.save({ ...state, planDrafts: state.planDrafts.map((plan) => plan.id === planId ? { ...plan, status, outcomeRecordedAt: now() } : plan) }); }
  updatePrivacySettings(input: Partial<PrivacySettings>): WorkspaceState { const state = this.load(); return this.save({ ...state, privacySettings: { ...state.privacySettings, ...input, updatedAt: now() } }); }
  deleteFriend(friendId: Id): WorkspaceState { const state = this.load(); const noteIds = new Set(state.notes.filter((note) => note.friendIds.includes(friendId)).map((note) => note.id)); const momentIds = new Set(state.momentCandidates.filter((moment) => moment.candidateFriendIds.includes(friendId)).map((moment) => moment.id)); return this.save({ ...state, friends: state.friends.filter((item) => item.id !== friendId), notes: state.notes.filter((item) => !item.friendIds.includes(friendId)), interactions: state.interactions.filter((item) => item.friendId !== friendId), momentCandidates: state.momentCandidates.filter((moment) => !moment.candidateFriendIds.includes(friendId)), confirmedHangouts: state.confirmedHangouts.filter((hangout) => !hangout.friendIds.includes(friendId) && !momentIds.has(hangout.momentCandidateId ?? "")), factProposals: state.factProposals.filter((item) => item.friendId !== friendId && !noteIds.has(item.sourceNoteId)), memoryFacts: state.memoryFacts.filter((item) => item.friendId !== friendId && !noteIds.has(item.sourceNoteId)), prompts: state.prompts.filter((item) => item.friendId !== friendId), planDrafts: state.planDrafts.filter((item) => item.friendId !== friendId), photoStars: state.photoStars.filter((star) => !momentIds.has(star.photoId)) }); }
}
